### ISSUE TITLE
'Configure puma' task fails as directory in {{ puma_config_path }} does not exist

### ISSUE THREAD

**Issue by fonglh** [andreychernih/railsbox#24]
The directories don't seem to be created yet.

**Comment by ferrisoxide** [comment]
@fonglh Had a similar issue with unicorn when provisioning on remote sites. In my setup I have two sets of config files, a `site.yml` for Vagrant and and `remote-site.yml` for production/staging. The main difference is the `remote-site.yml` includes the **deploy** role, inserted just before **webserver** (see example below). This at least ensures that the directories **webserver** needs are created, but does require a code deploy during the provision process. And it surfaces other issues.

I don't know Ansible very well, so this is all feels a bit hacky to me.  

```
- hosts: application
  handlers:
    - include: roles/delayed_job/handlers/main.yml
  roles:
    - base
    - { role: ruby, tags: ruby }
    - vim
    - deploy
    - webserver
```
